extend = "target/rust-driver-makefile.toml"

[env]
WDK_BUILD_ENABLE_SIGNTOOL_VERIFY = "true"

[config]
load_script = '''
#!@rust
//! ```cargo
//! [dependencies]
//! wdk-build = "0.4.0"
//! ```
#![allow(unused_doc_comments)]

wdk_build::cargo_make::load_rust_driver_makefile()?
'''